name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.21.1', '1.22.0', '1.23.0', '1.24.0']
    name: Go ${{ matrix.go }} run
    steps:
      - uses: actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          make install_revive

      - name: Run make ci
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -t .
          make ci
          make integration
          git status
          git diff > diff.log
          cat diff.log
          git clean -fd
          git reset --hard
          make verify
